# otel-collector-config.yaml
# docker run --rm -it -v $(pwd)/otel-collector-config.yaml:/etc/otelcol/config.yaml -p 4317:4317 -p 4318:4318  otel/opentelemetry-collector:latest
receivers:
  # Data sources: traces, metrics, logs
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  # Data sources: traces, metrics, logs
  file:
    path: ./otel/telemetry.json

  # Data sources: traces, metrics, logs
  # NOTE: Prior to v0.86.0 use `logging` instead of `debug`
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [debug, file]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [debug, file]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [debug, file]