auth_enabled: false

# This is to run Loki in a single process
target: all

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: debug
  grpc_server_max_concurrent_streams: 1000

common:
  instance_addr: loki
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    instance_addr: loki
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

limits_config:
  metric_aggregation_enabled: true

# compactor:
#   compaction_interval: 2h # or 1h

# query_scheduler:
#   use_scheduler_ring: false

# frontend:
#   scheduler_address: ""

# ingester:
#   lifecycler:
#     min_ready_duration: 0s
#   chunk_idle_period: 5m
#   chunk_retain_period: 30s

# distributor:
#   ring:
#     heartbeat_timeout: 10s
#     heartbeat_period: 5s

# compactor:
#   working_directory: /tmp/loki/compactor
#   shared_store: filesystem
#   compaction_interval: 10m

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
