services:
  database:
    image: pgvector/pgvector:pg16
    ports:
      - 5439:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      start_period: 10s
      timeout: 1s
      retries: 5
      interval: 5s
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    depends_on:
      database:
        condition: service_healthy
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8123:8000
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./backend:/backend
    env_file:
      - .env

  nginx_dev:
    image: nginx:alpine
    ports:
      - 8080:5173
    volumes:
      - ./nginx/nginx_dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
    driver: local