services:
  database:
    image: pgvector/pgvector:pg16
    ports:
      - 5439:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      start_period: 10s
      timeout: 1s
      retries: 5
      interval: 5s
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    depends_on:
      database:
        condition: service_healthy
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8123:8000
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./backend:/backend
    env_file:
      - .env

      
  # Telemetry Stack
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ../telemetry/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    command: ["--config", "/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"                   # OTLP gRPC
      - "4318:4318"                   # OTLP HTTP
      - "9464:9464"                   # Prometheus metrics
    depends_on:
      - prometheus
      - loki
      - tempo

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ../telemetry/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:latest
    container_name: loki
    user: "0:0"  # Run as root user
    volumes:
      - ../telemetry/loki-local-config.yaml:/etc/loki/local-config.yaml:ro
      - loki-data:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    user: "0:0"  # Run as root user
    volumes:
      - ../telemetry/tempo-local.yaml:/etc/tempo/tempo-local.yaml:ro
      - tempo-data:/tmp/tempo
    command: ["-config.file=/etc/tempo/tempo-local.yaml"]
    ports:
      - "3200:3200"   # HTTP query port

  phoenix:
    image: arizephoenix/phoenix:latest
    ports:
      - 6006:6006
    environment:
      - PHOENIX_WORKING_DIR=/mnt/data
    volumes:
      - phoenix_data:/mnt/data   # PHOENIX_WORKING_DIR

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin # default value
      - GF_SECURITY_ADMIN_PASSWORD=admin # default value
    volumes:
      - ../telemetry/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ../telemetry/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ../telemetry/grafana/dashboards/:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - tempo

  nginx_dev:
    image: nginx:alpine
    ports:
      - 8080:5173
    volumes:
      - ./nginx/nginx_dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
      - grafana

volumes:
  postgres_data:
    driver: local
  loki-data: {}
  tempo-data: {}
  phoenix_data:
    driver: local